import type {
  CommandCenterAccount,
  CommandCenterData,
  CommandCenterFirmGroup,
  CommandCenterSummary,
} from "./types";

// ─── Shared constants ──────────────────────────────────────────────────────────

const SYNC_MFF = new Date("2026-05-04T14:18:00.000Z");
const SYNC_LUCID = new Date("2026-05-04T14:20:00.000Z");

const MFF_FIRM_KEY = "myfundedfutures";
const MFF_FIRM_LABEL = "MyFundedFutures";
const MFF_CONN_ID = "demo-mff-tradovate-conn";

const LUCID_FIRM_KEY = "lucid trading";
const LUCID_FIRM_LABEL = "Lucid Trading";
const LUCID_CONN_ID = "demo-lucid-tradovate-conn";

// ─── MyFundedFutures accounts (5) ─────────────────────────────────────────────

const MFF_ACCOUNTS: CommandCenterAccount[] = [
  {
    id: "demo-mff-1",
    label: "MFF-E150-772341",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: MFF_FIRM_LABEL,
    firmKey: MFF_FIRM_KEY,
    firmLabel: MFF_FIRM_LABEL,
    accountType: "evaluation",
    accountTypeLabel: "Evaluation",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    status: "allowed",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 150_000,
    openPnl: 125,
    dailyPnl: 543,
    maxDailyLoss: 3_000,
    remainingDailyLoss: 3_000,
    dailyLossUsedPct: 0,
    tradesCount: 8,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 12,
    tradesUsedPct: 8 / 12,
    consecutiveLosses: 0,
    stopAfterLosses: null,
    lastSyncAt: SYNC_MFF,
    fillsSyncedAt: SYNC_MFF,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: false,
    setupNeededReason: null,
    breachReason: null,
    brokerConnectionId: MFF_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: null,
    lastInterventionTrigger: null,
    lastInterventionAt: null,
    hasOpenIntervention: false,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    id: "demo-mff-2",
    label: "MFF-E50-891203",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: MFF_FIRM_LABEL,
    firmKey: MFF_FIRM_KEY,
    firmLabel: MFF_FIRM_LABEL,
    accountType: "evaluation",
    accountTypeLabel: "Evaluation",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    // dailyLossUsedPct = 1050/1250 = 0.84 → warning
    status: "warning",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 50_000,
    openPnl: null,
    dailyPnl: -1_050,
    maxDailyLoss: 1_250,
    remainingDailyLoss: 200,
    dailyLossUsedPct: 1_050 / 1_250,
    tradesCount: 4,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 5,
    tradesUsedPct: 4 / 5,
    consecutiveLosses: 2,
    stopAfterLosses: null,
    lastSyncAt: SYNC_MFF,
    fillsSyncedAt: SYNC_MFF,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: true,
    setupNeededReason: null,
    breachReason: { headline: "Approaching daily loss limit" },
    brokerConnectionId: MFF_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: null,
    lastInterventionTrigger: null,
    lastInterventionAt: null,
    hasOpenIntervention: false,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    id: "demo-mff-3",
    label: "MFF-F150-334521",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: MFF_FIRM_LABEL,
    firmKey: MFF_FIRM_KEY,
    firmLabel: MFF_FIRM_LABEL,
    accountType: "funded",
    accountTypeLabel: "Funded",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    status: "allowed",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 150_000,
    openPnl: null,
    dailyPnl: 1_876,
    maxDailyLoss: 3_000,
    remainingDailyLoss: 3_000,
    dailyLossUsedPct: 0,
    tradesCount: 2,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 12,
    tradesUsedPct: 2 / 12,
    consecutiveLosses: 0,
    stopAfterLosses: null,
    lastSyncAt: SYNC_MFF,
    fillsSyncedAt: SYNC_MFF,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: false,
    setupNeededReason: null,
    breachReason: null,
    brokerConnectionId: MFF_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: null,
    lastInterventionTrigger: null,
    lastInterventionAt: null,
    hasOpenIntervention: false,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    id: "demo-mff-4",
    label: "MFF-F100-445632",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: MFF_FIRM_LABEL,
    firmKey: MFF_FIRM_KEY,
    firmLabel: MFF_FIRM_LABEL,
    accountType: "funded",
    accountTypeLabel: "Funded",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    // dailyLossUsedPct = 1.0 → locked
    status: "locked",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 100_000,
    openPnl: null,
    dailyPnl: -2_500,
    maxDailyLoss: 2_500,
    remainingDailyLoss: 0,
    dailyLossUsedPct: 1,
    tradesCount: 6,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 12,
    tradesUsedPct: 6 / 12,
    consecutiveLosses: 3,
    stopAfterLosses: null,
    lastSyncAt: SYNC_MFF,
    fillsSyncedAt: SYNC_MFF,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: true,
    setupNeededReason: null,
    breachReason: {
      headline: "Daily loss limit reached",
      detail: "This account is locked for the rest of the trading day.",
    },
    brokerConnectionId: MFF_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: "broker_locked",
    lastInterventionTrigger: "daily_loss_limit",
    lastInterventionAt: new Date("2026-05-04T13:47:00.000Z"),
    hasOpenIntervention: true,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    // Demo: locked, read-only connection — broker enforcement skipped.
    id: "demo-mff-4b",
    label: "MFF-F50-667890",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: MFF_FIRM_LABEL,
    firmKey: MFF_FIRM_KEY,
    firmLabel: MFF_FIRM_LABEL,
    accountType: "funded",
    accountTypeLabel: "Funded",
    connectionStatus: "connected_readonly",
    connectionStatusLabel: "Read-only",
    status: "locked",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 50_000,
    openPnl: null,
    dailyPnl: -1_800,
    maxDailyLoss: 1_800,
    remainingDailyLoss: 0,
    dailyLossUsedPct: 1,
    tradesCount: 4,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 12,
    tradesUsedPct: 4 / 12,
    consecutiveLosses: 2,
    stopAfterLosses: null,
    lastSyncAt: SYNC_MFF,
    fillsSyncedAt: SYNC_MFF,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: true,
    setupNeededReason: null,
    breachReason: {
      headline: "Daily loss limit reached",
      detail: "This account is locked for the rest of the trading day.",
    },
    brokerConnectionId: MFF_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: "unavailable_read_only",
    lastInterventionTrigger: "daily_loss_limit",
    lastInterventionAt: new Date("2026-05-04T13:52:00.000Z"),
    hasOpenIntervention: true,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    // Demo: locked, permission missing for Account Risk Settings.
    id: "demo-mff-4c",
    label: "MFF-F75-778901",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: MFF_FIRM_LABEL,
    firmKey: MFF_FIRM_KEY,
    firmLabel: MFF_FIRM_LABEL,
    accountType: "funded",
    accountTypeLabel: "Funded",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    status: "locked",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 75_000,
    openPnl: null,
    dailyPnl: -2_000,
    maxDailyLoss: 2_000,
    remainingDailyLoss: 0,
    dailyLossUsedPct: 1,
    tradesCount: 5,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 12,
    tradesUsedPct: 5 / 12,
    consecutiveLosses: 1,
    stopAfterLosses: null,
    lastSyncAt: SYNC_MFF,
    fillsSyncedAt: SYNC_MFF,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: true,
    setupNeededReason: null,
    breachReason: {
      headline: "Daily loss limit reached",
      detail: "This account is locked for the rest of the trading day.",
    },
    brokerConnectionId: MFF_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: "unavailable_permission",
    lastInterventionTrigger: "daily_loss_limit",
    lastInterventionAt: new Date("2026-05-04T13:55:00.000Z"),
    hasOpenIntervention: true,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    id: "demo-mff-5",
    label: "MFF-E25-556743",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: MFF_FIRM_LABEL,
    firmKey: MFF_FIRM_KEY,
    firmLabel: MFF_FIRM_LABEL,
    accountType: "evaluation",
    accountTypeLabel: "Evaluation",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    status: "setup_needed",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "none",
    rulesLabel: "No rules configured",
    balance: 25_000,
    openPnl: null,
    dailyPnl: null,
    maxDailyLoss: null,
    remainingDailyLoss: null,
    dailyLossUsedPct: null,
    tradesCount: null,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: null,
    tradesUsedPct: null,
    consecutiveLosses: null,
    stopAfterLosses: null,
    lastSyncAt: SYNC_MFF,
    fillsSyncedAt: SYNC_MFF,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: true,
    propFirmLimited: false,
    setupNeededReason: "prop_firm_rules_missing",
    breachReason: null,
    brokerConnectionId: MFF_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: null,
    lastInterventionTrigger: null,
    lastInterventionAt: null,
    hasOpenIntervention: false,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
];

// ─── Lucid Trading accounts (3) ───────────────────────────────────────────────

const LUCID_ACCOUNTS: CommandCenterAccount[] = [
  {
    id: "demo-lucid-1",
    label: "LT-F100-112233",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: LUCID_FIRM_LABEL,
    firmKey: LUCID_FIRM_KEY,
    firmLabel: LUCID_FIRM_LABEL,
    accountType: "funded",
    accountTypeLabel: "Funded",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    status: "allowed",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 100_000,
    openPnl: 340,
    dailyPnl: 1_243,
    maxDailyLoss: 2_000,
    remainingDailyLoss: 2_000,
    dailyLossUsedPct: 0,
    tradesCount: 3,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 10,
    tradesUsedPct: 3 / 10,
    consecutiveLosses: 0,
    stopAfterLosses: null,
    lastSyncAt: SYNC_LUCID,
    fillsSyncedAt: SYNC_LUCID,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: false,
    setupNeededReason: null,
    breachReason: null,
    brokerConnectionId: LUCID_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: null,
    lastInterventionTrigger: null,
    lastInterventionAt: null,
    hasOpenIntervention: false,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    id: "demo-lucid-2",
    label: "LT-F100-223344",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: LUCID_FIRM_LABEL,
    firmKey: LUCID_FIRM_KEY,
    firmLabel: LUCID_FIRM_LABEL,
    accountType: "funded",
    accountTypeLabel: "Funded",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    status: "allowed",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 100_000,
    openPnl: null,
    dailyPnl: -234,
    maxDailyLoss: 2_000,
    remainingDailyLoss: 1_766,
    dailyLossUsedPct: 234 / 2_000,
    tradesCount: 7,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 10,
    tradesUsedPct: 7 / 10,
    consecutiveLosses: 1,
    stopAfterLosses: null,
    lastSyncAt: SYNC_LUCID,
    fillsSyncedAt: SYNC_LUCID,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: false,
    setupNeededReason: null,
    breachReason: null,
    brokerConnectionId: LUCID_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: null,
    lastInterventionTrigger: null,
    lastInterventionAt: null,
    hasOpenIntervention: false,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
  {
    id: "demo-lucid-3",
    label: "LT-E50-334455",
    platform: "tradovate",
    platformLabel: "Tradovate",
    propFirm: LUCID_FIRM_LABEL,
    firmKey: LUCID_FIRM_KEY,
    firmLabel: LUCID_FIRM_LABEL,
    accountType: "evaluation",
    accountTypeLabel: "Evaluation",
    connectionStatus: "connected_live",
    connectionStatusLabel: "Connected",
    // dailyLossUsedPct = 2100/2500 = 0.84 → warning
    status: "warning",
    enforcementMode: "broker_readonly",
    permissionLevel: "read_only",
    ruleSource: "account",
    rulesLabel: "Account override",
    balance: 50_000,
    openPnl: null,
    dailyPnl: -2_100,
    maxDailyLoss: 2_500,
    remainingDailyLoss: 400,
    dailyLossUsedPct: 2_100 / 2_500,
    tradesCount: 9,
    tradesMayIncludePreConnection: false,
    tradeCountSource: "verified",
    maxTradesPerDay: 10,
    tradesUsedPct: 9 / 10,
    consecutiveLosses: 3,
    stopAfterLosses: null,
    lastSyncAt: SYNC_LUCID,
    fillsSyncedAt: SYNC_LUCID,
    balanceLimitedWarning: false,
    balanceUnavailableForBudget: false,
    propFirmSetupNeeded: false,
    propFirmLimited: true,
    setupNeededReason: null,
    breachReason: { headline: "Approaching daily loss limit" },
    brokerConnectionId: LUCID_CONN_ID,
    brokerEnv: "live",
    brokerLockStatus: null,
    lastInterventionTrigger: null,
    lastInterventionAt: null,
    hasOpenIntervention: false,
    flattenStatus: null,
    protectionStatus: "protected",
    pendingProtectionStatus: null,
    pendingProtectionEffectiveDate: null,
    missingFromBrokerSince: null,
    isLockedForToday: false,
    requiresAutomatedActionsConsent: false,
  },
];

// ─── Groups ────────────────────────────────────────────────────────────────────

const MFF_GROUP: CommandCenterFirmGroup = {
  groupId: `${MFF_FIRM_KEY}::${MFF_CONN_ID}`,
  firmKey: MFF_FIRM_KEY,
  firmLabel: MFF_FIRM_LABEL,
  accounts: MFF_ACCOUNTS,
  // allowed: mff-1, mff-3 · warning: mff-2 · locked: mff-4, mff-4b, mff-4c · setup_needed: mff-5
  counts: { allowed: 2, warning: 1, locked: 3, setup_needed: 1, not_connected: 0, unavailable: 0 },
  // dailyPnl: 543 + (-1050) + 1876 + (-2500) + (-1800) + (-2000) = -4931
  totalDailyPnl: -4_931,
  // remaining: 3000 + 200 + 3000 + 0 + 0 + 0 = 6200  (locked accounts have 0 remaining)
  totalRiskRemaining: 6_200,
  hasPnlData: true,
  hasRiskData: true,
  platform: "tradovate",
  platformLabel: "Tradovate",
  connectionStatus: "connected_live",
  connectionStatusLabel: "Connected",
  brokerConnectionId: MFF_CONN_ID,
  brokerEnv: "live",
  lastSyncAt: SYNC_MFF,
  enforcementMode: "broker_readonly",
};

const LUCID_GROUP: CommandCenterFirmGroup = {
  groupId: `${LUCID_FIRM_KEY}::${LUCID_CONN_ID}`,
  firmKey: LUCID_FIRM_KEY,
  firmLabel: LUCID_FIRM_LABEL,
  accounts: LUCID_ACCOUNTS,
  // allowed: lucid-1, lucid-2 · warning: lucid-3
  counts: { allowed: 2, warning: 1, locked: 0, setup_needed: 0, not_connected: 0, unavailable: 0 },
  // dailyPnl: 1243 + (-234) + (-2100) = -1091
  totalDailyPnl: -1_091,
  // remaining: 2000 + 1766 + 400 = 4166
  totalRiskRemaining: 4_166,
  hasPnlData: true,
  hasRiskData: true,
  platform: "tradovate",
  platformLabel: "Tradovate",
  connectionStatus: "connected_live",
  connectionStatusLabel: "Connected",
  brokerConnectionId: LUCID_CONN_ID,
  brokerEnv: "live",
  lastSyncAt: SYNC_LUCID,
  enforcementMode: "broker_readonly",
};

// ─── Summary ───────────────────────────────────────────────────────────────────

const ALL_ACCOUNTS = [...MFF_ACCOUNTS, ...LUCID_ACCOUNTS];

const DEMO_SUMMARY: CommandCenterSummary = {
  totalActive: ALL_ACCOUNTS.length,
  counts: { allowed: 4, warning: 2, locked: 3, setup_needed: 1, not_connected: 0, unavailable: 0 },
  breakdown: {
    allowed: { total: 4, live: 2, practice: 2 },
    warning: { total: 2, live: 1, practice: 1 },
    locked: { total: 3, live: 2, practice: 1 },
    setup_needed: { total: 1, live: 0, practice: 1 },
    not_connected: { total: 0, live: 0, practice: 0 },
    unavailable: { total: 0, live: 0, practice: 0 },
  },
  // totalDailyPnl: MFF -4931 + LUCID -1091 = -6022
  totalDailyPnl: -6_022,
  totalRiskRemaining: 10_366,
  openInterventions: 3,
  hasPnlData: true,
  hasRiskData: true,
  oldestSyncAt: null,
};

// ─── Export ────────────────────────────────────────────────────────────────────

export const DEMO_COMMAND_CENTER_DATA: CommandCenterData = {
  accounts: ALL_ACCOUNTS,
  groups: [MFF_GROUP, LUCID_GROUP],
  summary: DEMO_SUMMARY,
  firms: [
    { key: MFF_FIRM_KEY, label: MFF_FIRM_LABEL },
    { key: LUCID_FIRM_KEY, label: LUCID_FIRM_LABEL },
  ],
  pendingAccounts: [],
  reclassifiableAccounts: [],
  protectionLock: {
    isLocked: false,
    cutoffTime: null,
    tradingDayKey: "2026-05-04",
    nextTradingDayKey: "2026-05-05",
    hasSessionHours: false,
  },
};
